### PR TITLE
You missed a crucial point.

### PR DESCRIPTION
**Pull request by ThatJerk**

### CODE REVIEW

**Comment by MhikeiMPC** [comment]
I also have a reason why i dislike ImagicalMine. They are trying to cut off Genisys users from downloading plugins, when they copied nearly all their code from genisys. What kind of bullshit is that?>

**Comment by iPocket** [comment]
@ThatJerk is @DALTONTASTIC's alt account.
@keithkfng probably...

**Comment by DALTONTASTIC** [comment]
Actually this is my only Github account. Stop pretending you know anything because you don't.

**Comment by Aericio** [comment]
@DALTONTASTIC = g0d

**Comment by MhikeiMPC** [comment]
Dont say shit unless you can prove it.

**Comment by TonyWAV** [comment]
lol @DALTONASTIC is it true?

**Comment by DarkWav** [comment]
YEAH DALTONASTIC ur NOT Fair XD we credit pocketmine LOL we DON`T copy everything  from
Genisys (YOU`LL HAVE TO PROOF THAT! (This is impossible >XD)) 

@DALTONTASTIC said:

ImagicalMine completely disregards the progress that PocketMine-MP has made, and repackages it's code as their own.
# This is the BEST LIE i have EVER seen LOLOLOLOLOL XD

@DALTONTASTIC said:

ImagicalMine doesn't offer anything custom. All of their contributions are copied directly off the Genisys branch.

# I can only say you cant proof that anyway...

@DALTONTASTIC said:

Keith has no coding knowledge whatsoever. He literally just whines to his developers in the issue tracker until somebody finds some Genisys code to copy & paste.

# thats of course VERY true. i thing you know nothing ablout kieth...

# At the end i can only say, if you ban fe from the repo, i´ll laugh so loud about you.
# Noone of imagicalMine cares and and I HATE you @DALTONASTIC because 3 of the 5 reasons you gou give for taking over this repos are LIES!
# You will LOLOLOLOLOL ban me from the repo but i won´t care because i have done Everything wich must be done.
# @Aericio i completly  disagree...
# If someone say ImagicalMine copies from genisys he MUST proof it.
# Yeah, you heard my opinion what you did, gonna prevent all my plugins from working on pocketmine-mp (Note that i made the MOST downloaded plugin on Imagicalmine forums XD)
# Angry regards, DARKU

**Comment by Aericio** [comment]
ImagicalMine + Genisys = LagicalMinisys = Lag, Your 1 core that Genisys runs on will be 100%+ usage, Your ImagicalMine will be horrible since they have a lot more bugs, and probably if you homehost this your computer is going to overheat.

**Comment by MhikeiMPC** [comment]
Umm, actually, I use Genisys and my load is 10% with 30+ plugins and 11 players online, so why dont you actually run genisys instead of guessing!

**Comment by Aericio** [comment]
So why don't you go get 75 players and put them all in one server and run more than 50 plugins and actually run genisys like that instead of thinking that genisys is pro.

**Comment by SalmonGER** [comment]
I also runned Genisys on a whitelisted server. My load went to 117,6 % and the tempeture was 85°C.

**Comment by DarkWav** [comment]
@DALTONTASTIC, you should read that... https://forums.imagicalmine.net/threads/imagicalmine-community-forums-update.1355/
How ever, i think ImagicalTom is not a bad person.....
ImagicalMine is officially Dead. there´s no reason why this repositry exists anymore.
ImagicalMine went a completly new thing wich - i think - youn will like.
-Darku

**Comment by MhikeiMPC** [comment]
Done. my load was averagely 50-60. So why don't you go and upgrade your pc instead of using Intel Penimum 4?

**Comment by MhikeiMPC** [comment]
Its also funny how Keith is saying "Dalton uses Genisys!" When ImagicalMine is basically genisys lol!

**Pull request closed without merging**
