### PR TITLE
code cleanup, reorder methods in Item , move ID settings to new class ItemContainer

### PR DESCRIPTION
**Pull request by ecoron**
this is the first iteartion for code cleanup.
changes:
- Item extends new class ItemContainer
- ItemContainer holds all the ItemID and item related settings
- Item methods are reordered  (alphabetic)
- removed tabs and ascii header

so far i see after my testings, nothing should be breaked.
But would be nice if some other devs takes a look on it and can give some feedback.

### CODE REVIEW

**Comment by mwvent** [comment]
Tried on my test server did some basic tests no issues found :+1:

**Comment by keithkfng** [comment]
@ecoron Awesome!

**Comment by keithkfng** [comment]
About the CustomAlerts outdated client thingy, would this help? https://github.com/ItalianDevs4PM/Yuriko-MP/commit/2ad4e865b09cc5cd7b24b039504eeb3021362c1a

**Comment by AryToNeX** [comment]
@keithkfng You must not copy our code according to CC 4.0 International License.

**Comment by ecoron** [comment]
@keithkfng for the CustomAlerts thingy, i think we have already done a similar approach, but didn't checked it in detail yet, so according to the CC license there is no need to copy that :)

**Comment by PocketKiller** [comment]
:+1:, maybe we just make ItemContainer an interface with all item constants? and put back the function on Item class?

**Comment by dterweij** [comment]
Just a question, the code in general is LGPL from PM. Is it allowed to change a code license from a clone? To be honest, it are all clones. Tho there are additional hacks to the clones, LGPL, all code changes must be public and can be used by the public. So the CC 4.0 makes no sense at all because the original is LGPL and i believe it is not allowed to change it for clones, unless it is made closed source (make it zend/ioncube coded and VC not on a public VC website)

**Comment by dterweij** [comment]
Just read the LGPL rules, and all clones must follow the same license as its original. PocketMine-MP has its rights and may use all the code that are changed from all the clones. Same as for clones, all clones may use each others code. So @AryToNeX you are violating the PocketMine-MP License :)

**Comment by ecoron** [comment]
@PocketKiller yes this might be better. I would also reduce the hunderts of lines for setting items to tabs and so on. This can be configured in the interface as arrays and the methods can then loop thru this.

**Comment by AryToNeX** [comment]
@dterweij The PocketMine-MP base of our project is under LGPL but our implementations and changes are under CC, and LGPL permits us to do it, so we are not violating PocketMine-MP License because (I repeat) we are not changing the License of original PocketMine-MP source code, but we are applying CC only to our code/modifications/implementations. So you are trying all the methods to copy the code from us or am I wrong?

**Comment by PocketKiller** [comment]
@ecoron I'll try to make a .json with create items and decode them.

**Comment by ecoron** [comment]
It becomes a little bit off topic here. So I will merge and close this now. @PocketKiller  ok cool, and all other changes can be done afterwards. @AryToNeX  no we don't try to copy something. @keithkfng shows only a commit and how it was solved there.  that's it

**Comment by BlackShadow1** [comment]
@ecoron "About the CustomAlerts outdated client thingy, would this help? ItalianDevs4PM/Yuriko-MP@2ad4e86", it's a try to copy the code from Yuriko, it's clear that @keithkfng says the code from Yuriko can help, so he want to copy some code, @AryToNeX was right, you want to violate CC 4.0.

**Comment by ecoron** [comment]
i'm to lazy for this discussion, we have nearly the same approach commited a week ago, @AryToNeX  commit is just one day old. so what should we try to copy? it's the nature of open source to get inspirations from other projects.

**Comment by AryToNeX** [comment]
@ecoron YOU WERE RIGHT. Inspirations, not "copy" and "paste" of code. I mean that we don't want our code to get copied.

**Comment by keithkfng** [comment]
@BlackShadow1 see, this is your inference. I have said "would this help", and never said anything about copying code. This is the example of spelling "waht si my piont" but the brain converts it to "what is my point"

**Pull request merged**
