### PR TITLE
onPlayerAction-patch-1 - add generic method to Item/Entity

### PR DESCRIPTION
**Pull request by ecoron**
add generic method onPlayerAction to Item and Entity
- prepared for moving Item/Entity specific logic from Player to the right place, instead blowing it up with "if else" statements to handle Item/Entity based logic.
- it's doing nothing add the moment
- i will use it later for the required logic in Minecart classes and maybe Boat classes too
- should be usefull to cleanup Player class
- tested on my dev server

### CODE REVIEW

**Comment by PocketKiller** [comment]
Dang it, you mess up the ASCII

**Comment by ecoron** [comment]
ah, i see. will fix it.

**Comment by keithkfng** [comment]
👍🏻

**Comment by ecoron** [comment]
thx, so I can go on with Minecart...

**Comment by keithkfng** [comment]
I think it's causing conflicts - would you mind submitting this to the 0.14 branch?

**Comment by keithkfng** [comment]
BTW @ecoron you were invited to the team so you can make direct commits, accept it @ https://github.com/ImagicalMine

**Comment by ecoron** [comment]
first thx for inviting. i joined :)
for this patch, i will create a new pr later for 14.0, there will be some more changes required to make minecard working. so i would say it's better to merge it later on.
btw. i can now breaking it and hop on/off works, but the movement is crazy...

**Pull request merged**
