### PR TITLE
MCPE 0.14 compatibility update

### PR DESCRIPTION
**Pull request by keithkfng**
Still a few more changes need to be pushed - but I'm creating this anyway...

DO NOT MERGE UNTIL AN OFFICIAL MCPE RELEASE IS RELEASED TO THE GENERAL PUBLIC.

### CODE REVIEW

**Comment by PocketKiller** [comment]
:DD

**Comment by PocketKiller** [comment]
wait DONT

**Comment by keithkfng** [comment]
@PocketKiller still can't join on 0.14 by the way...

**Comment by XFuryMCPE** [comment]
Try fixing the health bug. when someone is damaged, the hearts don't subtract on the screen. But they actually do go away, then when you die you can't respawn

**Comment by keithkfng** [comment]
@XFuryMCPE will do - create a new issue will be very helpful...

**Comment by lolcraftboy14** [comment]
Chunks downt load corect

**Comment by PocketKiller** [comment]
true

**Comment by PocketKiller** [comment]
they load but slow on 14.0 its MCPE Bug.

**Comment by thebigsmileXD** [comment]
xD its a mcpe bug? i think its IM being to slow xD

**Comment by robske110** [comment]
Hopefully it will get fixed in the final relase!

**Comment by GODLIKE5** [comment]
Hello @keithkng how do I upload a build to Jenkins?

**Comment by PocketKiller** [comment]
@GODLIKE5 You can't.

**Comment by applqpak** [comment]
I'll help convert it to MCPE 0.14.0!

**Comment by robske110** [comment]
We have conflicts now

**Comment by UltimateMcraft** [comment]
Can't you make a 'test build' so we can test it?

**Comment by SalmonGER** [comment]
http://jenkins.imagicalmine.net:8080/job/ImagicalMine-0.14/ Do you mean this?

**Comment by UltimateMcraft** [comment]
@SalmonGER Yes, I never saw it before.

**Comment by keithkfng** [comment]
@ecoron can you merge mcpe-0.14 into master, then php7 into master as well? Thanks.

**Comment by keithkfng** [comment]
@ImagicalMine/developers DO NOT COMMIT TO THE mcpe-0.14 BRANCH ANYMORE, PLEASE COMMIT TO THE php7-0.14 BRANCH. Thanks!

**Comment by ecoron** [comment]
@keithkfng just to clearify realy into master? I think it's better to make php7, php7-0.14 uptodate by merging the changes from master into it, so it should be easy to merge it later into master if 0.14 is rolled out.

**Comment by keithkfng** [comment]
@ecoron I didn't say master did I?

**Comment by XFuryMCPE** [comment]
Lmao

**Comment by ecoron** [comment]
btw. is there a way to hide the conversion from previous conversions/commits in the pull-request template, it's a little bit confusing.

**Comment by keithkfng** [comment]
Nope sorry.

**Pull request closed without merging**
