### PR TITLE
Doesn't work that way

### PR DESCRIPTION
**Pull request by ImagicalGamer**
- [x] This PR actually submits something - don't use this system as a messaging service!
- [x] This PR isn't duplicated - you can check if it is by scanning the small list - link is on the navigation bar for this repository.
- [ ] This PR includes appropriate markdown for sections - e.g. code blocks for suggested code.
- [ ] This PR description and comments in code is understandable - feel free to use your native language to write if you are not comfortable with English.
- [x] This PR matches the contributing guidelines - the link is just above the title field.
- [x] This PR has a single branch for itself in your fork - don't just commit to the master branch of your repository!
- [x] This PR has comments written in clear English - please don't write unreadable comments just for your eyes.
- [x] This PR has descriptive titles for commits - don't use "Updated <file-name>" as your title for all your commits in the PR.
- [x] This PR contains appropriate credit and clearly states the source in the description of commits.

## Optional information
Correct me if I'm wrong but, pocketmine\utils\UUID should handle that, I run a private fork of this on my server and that's what we use. It works better for adding entity packets

### CODE REVIEW

**Comment by remotevase** [comment]
What do you mean? It seems to work fine already... Are you **_sure_** that it works?

**Comment by keithkfng** [comment]
Maybe test this first... Are you sure it works? Apparently Travis thinks so, so...

**Comment by remotevase** [comment]
But Travis doesn't check when q player joins our leaves

**Comment by Taki21** [comment]
Dont Delete Branch just in case,,,

**Comment by Taki21** [comment]
if we revert xD

**Pull request merged**
