### PR TITLE
Add recipes for flowers -> dye.

### PR DESCRIPTION
**Pull request by leonardosnt**
- [X] This PR actually submits something - don't use this system as a messaging service!
- [X] This PR isn't duplicated - you can check if it is by scanning the small list - link is on the navigation bar for this repository.
- [X] This PR includes appropriate markdown for sections - e.g. code blocks for suggested code.
- [X] This PR description and comments in code is understandable - feel free to use your native language to write if you are not comfortable with English.
- [X] This PR matches the contributing guidelines - the link is just above the title field.
- [X] This PR has a single branch for itself in your fork - don't just commit to the master branch of your repository!
- [X] This PR has comments written in clear English - please don't write unreadable comments just for your eyes.
- [X] This PR has descriptive titles for commits - don't use "Updated <file-name>" as your title for all your commits in the PR.

--------------------

Add recipes for flowers to your respective dyes, according with singleplayer/wiki.

Sorry for my english.

### CODE REVIEW

**Comment by keithkfng** [comment]
Looks good.

**Comment by leonardosnt** [comment]
Yeh

**Comment by leonardosnt** [comment]
@keithkfng if possible, see my PM on gitter.

Thanks;

**Comment by keithkfng** [comment]
Saw it and replied to it. It's alright where it is - is it possible for you to clean up the code base a bit and lessen lag?

**Comment by leonardosnt** [comment]
Sorry, i didn't understand, you mean this code?

**Comment by Creeperface01** [comment]
You can use for loop i think it would be better

**Comment by keithkfng** [comment]
@leonardosnt no, like the overall code. Not just this file or PR code.

**Comment by leonardosnt** [comment]
@keithkfng Ok.

@Creeperface01 Yes, i thought about that, but i think that this way is more readable, and will not affect performance.

**Comment by keithkfng** [comment]
@leonardosnt see my PM on Gitter.

**Comment by 0-Eclipse-0** [comment]
Add him to the team. He knows php so he'd be a good contributor. Also, I hate having to review pull requests lol.

**Comment by keithkfng** [comment]
Okay.

**Pull request merged**
