### PR TITLE
Fast BugFix for onPlayerAction

### PR DESCRIPTION
**Pull request by robske110**
Hacky, should be reverted later

### CODE REVIEW

**Comment by robske110** [comment]
There is am new checker wich does not work lol

**Comment by BlackShadow1** [comment]
It doesn't work. :D

**Comment by ecoron** [comment]
I'm just added the fix for #821 and also #841 :) target must be instance of entity or item eher onPlayerAction is implemented.

**Comment by robske110** [comment]
good (This was just an quick fix)

**Pull request closed without merging**
