### PR TITLE
Remove duplicate file at "invalid" namespace.

### PR DESCRIPTION
**Pull request by leonardosnt**
- [x] This PR actually submits something - don't use this system as a messaging service!
- [x] This PR isn't duplicated - you can check if it is by scanning the small list - link is on the navigation bar for this repository.
- [x] This PR includes appropriate markdown for sections - e.g. code blocks for suggested code.
- [x] This PR description and comments in code is understandable - feel free to use your native language to write if you are not comfortable with English.
- [x] This PR matches the contributing guidelines - the link is just above the title field.
- [x] This PR has a single branch for itself in your fork - don't just commit to the master branch of your repository!
- [x] This PR has comments written in clear English - please don't write unreadable comments just for your eyes.
- [x] This PR has descriptive titles for commits - don't use "Updated <file-name>" as your title for all your commits in the PR.

--------------------

Remove src/pocketmine/INVENTORY/CraftItemEvent.php that is duplicate of pocketmine/event/inventory/CraftItemEvent.php

Fix typo & fix header

### CODE REVIEW

**Comment by 0-Eclipse-0** [comment]
The spelling error doesn't in any way effect ImagicalMine. It is just a preference.

**Comment by leonardosnt** [comment]
@0-Eclipse-0 "Duplicated file" you dont read?

**Comment by leonardosnt** [comment]
I really think that you need to read commit & PR messages before replying.

**Comment by 0-Eclipse-0** [comment]
@leonardosnt I do read the pull requests.

**Pull request closed without merging**
