### PR TITLE
merge master into php7

### PR DESCRIPTION
**Pull request by ecoron**
i think now the changes from master are in php7 branch - #847.

i didn't merged it finaly yet, so you can take a look on the changes and check
if i something have forgotten or changed it in the wrong way, because there was a lot of conflicts.

If anything is fine it can merged into the origin branch php7.

### CODE REVIEW

**Comment by ecoron** [comment]
hmm didn't get it, whats wrong?... error from Travis log
```
Warning: Declaration of pocketmine\block\NetherPortal::place(pocketmine\item\Item $item, pocketmine\block\Block $block, pocketmine\block\Block $target, $face, $fx, $fy, $fz, pocketmine\block\Player $player = NULL) should be compatible with pocketmine\block\Block::place(pocketmine\item\Item $item, pocketmine\block\Block $block, pocketmine\block\Block $target, $face, $fx, $fy, $fz, pocketmine\Player $player = NULL) in /home/travis/build/ImagicalMine/ImagicalMine/src/pocketmine/block/NetherPortal.php on line 65
```

**Comment by rWardy** [comment]
Missing
```
use pocketmine\Player
```
from NetherPortal.php?

**Comment by ecoron** [comment]
Ahh thx. That was missing.

**Comment by ecoron** [comment]
any ideas?
RakLib crashes at the end of travis build

```
20:04:46] system> ImagicalMine 1.0dev Phar file has been created on /home/travis/build/ImagicalMine/ImagicalMine/plugins/DevTools//ImagicalMine_1.0dev.phar
[20:04:46] system> [CONSOLE: Stopping the server]
[20:04:46] system> Disabling DevTools v1.9.0
[20:04:46] system> Unloading level "world"
**[20:04:47] emergency> RakLib crashed!**
[20:04:47] system> Stopping other threads
```

**Comment by keithkfng** [comment]
As long as it builds, I'm fine with that crash :)

**Comment by ecoron** [comment]
ok cool, i think ist somewhere in server.php

**Pull request merged**
