### PR TITLE
Generate flowers

### LINKED ISSUE #837: Level generates without flowers
I'm having a look at the generator and have tried to put in flowers (as a starting point).  Can you have a look at my initial commit to see if I am going down the correct road. It seems to work for the biomes I have added, but want to know if there is a better/correct way of doing it:  I've tried to work with TallGrass as an example, but also needed a way of always having a Flowers populator (as there are defaults when none are specified in the specific Biome)

https://github.com/rWardy/ImagicalMine/commit/8448b9d4c3b31597444b8c5904f1a40c6f6d93a5

Once I've got this right I'll start adding other ground based stuff such as bushes, cacti, sugarcane etc.

Thanks

### PR DESCRIPTION
**Pull request by rWardy**
OK guys, first attempt at adding something completely new  This is designed to generate flowers when the world is built.  Comments appreciated on the approach.
Basically flowers should not generate in all biomes based on data from http://minecraft.gamepedia.com/Flower (Sunflower Plain and Flower Forest excluded).

If you think I should add the defaults in a different way than in Biome,php then let me know.  Have modelled the process on TallGrass.

Next steps following this is to add some way to determine the block a flower can be spawned on so Dead Bushes, Cacti and Sugar Cane can be added for the desert biome.

fix #837

### CODE REVIEW

**Comment by rWardy** [comment]
@keithkfng I'm assuming the failed checks are something you are working on :P

**Comment by keithkfng** [comment]
Yes - ignore Circle CI and AppVeyor for now.

**Comment by matcracker** [comment]
Uh, nice. If you test, merge it.

**Comment by rWardy** [comment]
Been tested, it was more the approach I was checking.  Will merge later depending on further feedback.

**Pull request merged**
