### PR TITLE
Added Clear Screen on startup, Fixes Spelling

### PR DESCRIPTION
**Pull request by dc4code**
- [ ] This PR actually submits something - don't use this system as a messaging service!
- [ ] This PR isn't duplicated - you can check if it is by scanning the small list - link is on the navigation bar for this repository.
- [ ] This PR includes appropriate markdown for sections - e.g. code blocks for suggested code.
- [ ] This PR description and comments in code is understandable - feel free to use your native language to write if you are not comfortable with English.
- [ ] This PR matches the contributing guidelines - the link is just above the title field.
- [ ] This PR has a single branch for itself in your fork - don't just commit to the master branch of your repository!
- [ ] This PR has comments written in clear English - please don't write unreadable comments just for your eyes.
- [ ] This PR has descriptive titles for commits - don't use "Updated <file-name>" as your title for all your commits in the PR.
- [ ] This PR contains appropriate credit and clearly states the source in the description of commits.

## Optional information

+Added Clear Screen on startup
+Fixes Spelling

### CODE REVIEW

**Comment by remotevase** [comment]
Does Travis-CI use start.sh or start.cmd?
Can someone test this please? Thanks for the spelling, but the clear screen? Necessary or not?

**Comment by keithkfng** [comment]
Travis uses another start file... Is this really necessary?

**Comment by remotevase** [comment]
Okay, thanks. Now, what does the clear screen do? Based on my limited research, all it does is slow down the startup process

**Comment by remotevase** [comment]
Closing PR. Pushing spelling fix, but not the clear screen

**Pull request closed without merging**
