### PR TITLE
Fixed Slapper CRASH

### PR DESCRIPTION
**Pull request by robske110**
@thebigsmileXD  You did this :(
I think you "lagged" on this too: https://github.com/ImagicalCorp/ImagicalMine/commit/0f19b1d9c5cb233902a5ba929386f884c089f94d#diff-d32fe31d118541ac4628b565b81ae7f1R216

### CODE REVIEW

**Comment by robske110** [comment]
And the functions addItem and removeItem should be removed! (They are not in org Pocketmine and they are crashing too!)

**Comment by robske110** [comment]
No one has an comment?

**Comment by PocketKiller** [comment]
hmm

**Comment by thebigsmileXD** [comment]
You know these functions are official PM functions used in some plugins? LimitedCreative, instantbreak etc?

**Comment by PocketKiller** [comment]
True

**Comment by robske110** [comment]
Will you merge this? And it doesnot remove addItem and removeItem i'm just saying that they will crash too and they are NOT in offical pocketmine
But the setItem function wss fixed now!

**Comment by robske110** [comment]
https://github.com/PocketMine/PocketMine-MP/blob/master/src/pocketmine/inventory/PlayerInventory.php

**Comment by thebigsmileXD** [comment]
Additem and removeitem are, i'll send you a documentation link later if you want

**Comment by robske110** [comment]
But not in that file

**Comment by robske110** [comment]
Anyway, wilk you merge this? It just fixes setItem it does not remove addItem or removeItem i just said that it does not belong in PlayerInventory.php (look in the link!)

**Comment by robske110** [comment]
Oops

**Comment by robske110** [comment]
Will you merge this or not?

**Comment by thebigsmileXD** [comment]
Will you spam more or not?

**Comment by kiyoshi-kurosaki** [comment]
I don't know what the problem is, but works correctly and doesn't be merged

**Comment by robske110** [comment]
Did not understand that english @kiyoshi-kurisaki

**Comment by keithkfng** [comment]
Is this tested with plugins? I think from the response of the above that this doesn't need to be merged and will cause plugin crashes.

**Comment by ZombiePower** [comment]
don't merge it in....

**Comment by robske110** [comment]
Look at this file, again https://github.com/PocketMine/PocketMine-MP/blob/master/src/pocketmine/inventory/PlayerInventory.php (The line i commented out is not existing there! So it will not cause ANY plugins to crash IT F I X E S the plugin crashes on setItem)
And I do not find addItem and removeItem anywhere in that file and i didn't even deleted these functions, but the server would crash too (If an plugin calls these functions, but no plugin would do that as they do not exist!)

**Comment by robske110** [comment]
What "Thanks"?

**Comment by robske110** [comment]
Is that better?

**Comment by keithkfng** [comment]
I think @Driesboy's PR would be better, because it checks for players, not NULL...

**Comment by robske110** [comment]
Yes this pr doesn't help

**Pull request closed without merging**
