### PR TITLE
incorrect meta of slab and double slab

### PR DESCRIPTION
**Pull request by intagaming**
Ermmmm first time use Github ...
http://minecraft.gamepedia.com/Slab

### CODE REVIEW

**Comment by intagaming** [comment]
Sorry i was do something wrong ...

**Comment by robske110** [comment]
Delete that commit

**Comment by intagaming** [comment]
@robske110 help meeee how to delete it ...

**Comment by matcracker** [comment]
Do you test it?

**Comment by intagaming** [comment]
@matcracker  Test with the 1bf38db, but now i want to delete the ca94f09 , can you help me ? ...

**Comment by ecoron** [comment]
wtf, 980 files changed? seems it's from a complete different source, delete this branch and only commit the files you have changed by yourself(not IDE) to a new one, from this you can try to start again making a pull request.

some nice tutorial about git: https://try.github.io

**Comment by PocketKiller** [comment]
its better that you haven't reverted that commit.

**Comment by ecoron** [comment]
yes, the first one looks ok. https://github.com/intagaming/ImagicalMine/commit/1bf38db016366679c6ebd36704dccd34ccf80684
maybe you make a hard reset to this one

**Comment by intagaming** [comment]
@ecoron hnmm looks like im done with your guide. Thank you and to another too!
Okay im tested with this commit.

**Comment by PocketKiller** [comment]
Okay ;)

**Pull request merged**
