### PR TITLE
Delete start.sh

### PR DESCRIPTION
**Pull request by majovec**
- [x] This PR actually submits something - don't use this system as a messaging service!
- [x] This PR isn't duplicated - you can check if it is by scanning the small list - link is on the navigation bar for this repository.
- [x] This PR includes appropriate markdown for sections - e.g. code blocks for suggested code.
- [ ] This PR description and comments in code is understandable - feel free to use your native language to write if you are not comfortable with English.
- [ ] This PR matches the contributing guidelines - the link is just above the title field.
- [ ] This PR has a single branch for itself in your fork - don't just commit to the master branch of your repository!
- [ ] This PR has comments written in clear English - please don't write unreadable comments just for your eyes.
- [ ] This PR has descriptive titles for commits - don't use "Updated <file-name>" as your title for all your commits in the PR.
- [ ] This PR contains appropriate credit and clearly states the source in the description of commits.

### CODE REVIEW

**Comment by majovec** [comment]
grd

**Comment by leonardosnt** [comment]
Why??

**Comment by majovec** [comment]
Fucking ImagicalMine !!!! AllMine is best ( funion enhant,mobs,real nether,

**Comment by leonardosnt** [comment]
@majovec What, you are retarded? It is just a pull request, you are not changing anything on ImagicalMine

**Pull request closed without merging**
