### PR TITLE
more versions support

### PR DESCRIPTION
**Pull request by Driesboy**

### CODE REVIEW

**Comment by PocketKiller** [comment]
YOU CAN COMMIT DIRECTLY.

**Comment by PocketKiller** [comment]
don't commit this, you want to let 0.14.0 and 0.13.0 join together NO.

**Comment by ecoron** [comment]
will not work there is also a small change in the packets between 0.13 and 0.14

**Comment by PocketKiller** [comment]
@ecoron is also correct.

**Comment by Driesboy** [comment]
o ok

**Pull request closed without merging**
