### PR TITLE
Make Hunger Save and Load

### LINKED ISSUE #716: Hunger not saved on player disconnect
Please add saving of hunger amount when player disconnects, players currently disconnect and reconnect to reset hunger.

### PR DESCRIPTION
**Pull request by rWardy**
Hunger is not persisted across sessions. Should fix #716

### CODE REVIEW

**Comment by keithkfng** [comment]
Is this tested?

**Comment by DRedDogPE** [comment]
i can test it later if it isnt tested before then

**Comment by kiyoshi-kurosaki** [comment]
Not working, i tested it yesterday.

**Comment by rWardy** [comment]
Does work, but doesn't display straight away. Need to wait for next hunger tick after logging in to see the update client side.  Same happens on Health.  I can't find a way to force client to get correct health and food values from server. Anyone any ideas on this?

**Comment by rWardy** [comment]
Think I've sorted the not downloading to client. Does anybody know why on line 86 of entity\AttributeManager.php we clone the Attribute?

```PHP
return isset($this->attributes[$id]) ? clone $this->attributes[$id] : null;
```

This means that when an attribute is set (i.e. by setFood), it isn't set in the version of the Attribute stored in AttributeManager.  This means when SendAll is called in Player.php on line 1847:

```PHP
$this->getAttribute()->sendAll();
```

it sends the original version of the attribute that has it's value set as 20, not what has been set when I reload the value.

I'll carry on making changes and checking Health and EXP and then update the pull request with all the changes.  Let me know if anybody can think why the Attribute is cloned rather than returning the actual value.

**Comment by keithkfng** [comment]
I can tell you why - because it's from Katana LOL

**Comment by rWardy** [comment]
Does that mean I can't change it?

**Comment by rWardy** [comment]
OK, take a look at that and see what you think.  Should fix Health, Hunger and Experience

**Comment by rWardy** [comment]
Should fix #272 and #716

**Comment by keithkfng** [comment]
No harm in trying... Simply revert later if it doesn't work :P
@rWardy invited you to the team so you can push commits directly... Check your email.

**Comment by rWardy** [comment]
Thanks.  This mean I don't need PR for editing now?

**Comment by keithkfng** [comment]
Yep - you can push directly to the repo.

**Pull request merged**
