### PR TITLE
Fixes DevTools

### PR DESCRIPTION
**Pull request by jjplaying**
- [x] This PR actually submits something - don't use this system as a messaging service!
- [x] This PR isn't duplicated - you can check if it is by scanning the small list - link is on the navigation bar for this repository.
- [x] This PR includes appropriate markdown for sections - e.g. code blocks for suggested code.
- [x] This PR description and comments in code is understandable - feel free to use your native language to write if you are not comfortable with English.
- [x] This PR matches the contributing guidelines - the link is just above the title field.
- [x] This PR has a single branch for itself in your fork - don't just commit to the master branch of your repository!
- [x] This PR has comments written in clear English - please don't write unreadable comments just for your eyes.
- [x] This PR has descriptive titles for commits - don't use "Updated <file-name>" as your title for all your commits in the PR.
- [x] This PR contains appropriate credit and clearly states the source in the description of commits.

## Pull Request description

Fixes a bug because DevTool's makeplugin command does not work any more, because there is a own makeplugin command in ImagicalMine which does not work. With the fix, everything works now. Here's also a discussion about it: https://forums.imagicalmine.net/threads/please-remove-or-fix-makeplugin.796/

### CODE REVIEW

**Comment by jjplaying** [comment]
I think the crash in the build check is not caused by my pull request, looks like something with redstone repeater.

**Comment by remotevase** [comment]
Thanks... But the travis CI didn't work. Gonna check

**Comment by keithkfng** [comment]
Yep. @remotevase can you look into the src/pocketmine/block/RedstoneRepeater.php file and change Unlit to Unpowered?

**Comment by remotevase** [comment]
Ive been testingvarious fixes for that crash on my local machine, hardly any seem to work. Still trying to fix. If you rename to unlit to unpowered then it says missing unlit
EDIT: Possible bad quick fix found, may commit bit some tests required first

**Comment by keithkfng** [comment]
@remotevase I have fixed the repeaters myself, thanks for trying. You can look at my commits if you wish to see what I did to fix it. Mind testing this PR and merging it?

**Comment by remotevase** [comment]
@Keith I'll definitely take a look at ur commits so I can learn more
I'll test soon, but I have a huge list of other things that I have to do first

**Comment by remotevase** [comment]
@jjplaying can you do us a favor and submit this PR again? Makes our lives so much easier, as now Travis-CI can actually check YOUR pr for errors, and not the repeater

**Comment by jjplaying** [comment]
No problem, I'll do it

**Comment by remotevase** [comment]
thanks so much

**Pull request closed without merging**
