### PR TITLE
Grow correct tree from saplings

### LINKED ISSUE #805: Oak trees grow from acacia and dark oak saplings
An oak tree grows from acacia saplings and dark oak saplings and when you use bonemeal on a sapling it grows extremely small like a bush

### PR DESCRIPTION
**Pull request by rWardy**
fix #805

### CODE REVIEW

**Comment by keithkfng** [comment]
Pull request?!

**Comment by rWardy** [comment]
@keithkfng yeah, trying to do it properly (still getting to grips with full git suite).  Not a problem I've done it as Pull Request is it?

**Comment by keithkfng** [comment]
No, just a bit surprised you didn't commit directly XD

**Comment by rWardy** [comment]
:) I'm trying to get to grips with multiple branches in my fork and local repro, and then bringing branches up to date with later changes etc.

**Comment by thebigsmileXD** [comment]
Will the Acacia look like the pc ones?

**Comment by rWardy** [comment]
I think the look is controlled by the client, as long as the blocks are correct.  This should fix the correct wood block and leaves being used.  They looked different and dropped the correct blocks when i tested it.  Existing trees won't be affected though (i.e. if you had grown an acacia from a sapling it will still be oak after this fix), only new ones.

**Comment by thebigsmileXD** [comment]
@rWardy i mean will it have the high plattformed design or will it look like an oak tree (i talk about the shape)

**Comment by rWardy** [comment]
I copied one of the existing trees (can't remember which one), so it will look similar to existing, but at least they will grow :)

**Comment by thebigsmileXD** [comment]
i see xD

**Pull request merged**
