### PR TITLE
ImagicalMine-IC_Installer_1.6.2

### PR DESCRIPTION
**Pull request by ZenaGamingsky**
Hi i have made a ImagicalMine-IC_Installer_1.6.2 like pocketmine-mp installer took loads of work i am realy sorry for what i have done hope this helps you.

download file

http://www.mediafire.com/download/n11173ocp1jrg8d/ImagicalMine.zip

plz try it

### CODE REVIEW

**Comment by ChalkPE** [comment]
It's maybe just me, but where's the installer code?

**Comment by cr0sh** [comment]
Please provide a source code or packing instructions.

**Comment by keithkfng** [comment]
1. Don't submit pull requests that have nothing to do with what you're saying.
2. There is no IM 1.6.2 version. It's currently at 1.0dev.
3. Will you post the installer code as requested above?

**Comment by ZenaGamingsky** [comment]
I download sorry but I can't talk the chat down plz try it

**Comment by ZenaGamingsky** [comment]
Here
Un zip it run .exe http://www.mediafire.com/?n11173ocp1jrg8d

**Comment by ZenaGamingsky** [comment]
Yes I give you the .exe code of you want it

**Comment by ZenaGamingsky** [comment]
Yes I will the zip has the installer in it with your Serevr phar j give the source code latter

**Comment by ZenaGamingsky** [comment]
How do I add it to GitHub I have the code in a zip all of it can be download from http://www.mediafire.com/?n11173ocp1jrg8d

**Comment by ZenaGamingsky** [comment]
I will register the doamin free with go daddy this Friday and give you the login via email http://imagicalmine.net you want this one right

**Comment by ZenaGamingsky** [comment]
I can't get it not available can get http://imagicalmine.com

**Comment by ZenaGamingsky** [comment]
Yes the installer code I give you

**Comment by ZenaGamingsky** [comment]
Would you like to see imagicalmine server gui almost done

**Comment by ZenaGamingsky** [comment]
I can do .exe and learning php so Almost done and soon will be working on panelmine

**Comment by keithkfng** [comment]
Closing and locking. Read the contributing guidelines please - don't use the issue tracker or pull requests as a chatroom.

**Pull request closed without merging**
