### PR TITLE
Update Info.php

### PR DESCRIPTION
**Pull request by wsj7178**
for build3

### CODE REVIEW

**Comment by keithkfng** [comment]
Thanks.

**Comment by PocketKiller** [comment]
hmm.. build 3 changed protocol? i don't think so..

**Comment by SalmonGER** [comment]
@PocketKiller It did change.

**Comment by PocketKiller** [comment]
@SalmonGER Thanks for telling me, now where can I find build 3...

**Comment by SalmonGER** [comment]
@PocketKiller Just saying it because protocol version 42 is working with build 3 on my server, and protocol version 41 doesn't.

**Pull request merged**
