### PR TITLE
Probably fixes Issue #592

### PR DESCRIPTION
**Pull request by Taki21**
I dunno about the global thingy and main-limit but when making the compression level higher, the server doesn't have the memory crash! (have not seen any from testing on my server)

### CODE REVIEW

**Comment by keithkfng** [comment]
How many hours?

**Comment by Taki21** [comment]
9 hours already and no crashes! Usually like every few hours ... BOOM

**Comment by Taki21** [comment]
Also i would like to test without the global limit and main-limit, ill see what happens

**Comment by ecoron** [comment]
this settings depends on the available hardware. i would suggest its up to the server owner to figure out which settings are proper.

**Comment by Taki21** [comment]
And also the memory reached about a gig!
ice_screenshot_20160122-171120

**Comment by keithkfng** [comment]
@ecoron by the way, I fixed up the log writing issue.

**Comment by Taki21** [comment]
@ecoron  I think its based on the console (the software) not the hardware of the computer itself

**Comment by ecoron** [comment]
@keithkfng thx, but don't forget the ressources/pocketmine.yml. now is logging on by default maybe it should be disabled.

@Taki21 what i mean, it depends on how many cpu, memory is available on the instance where the software is running. 100 means it allocates max 100mb of memory - it's a setting for very small instances with less players

**Comment by keithkfng** [comment]
@ecoron yes, it's on by default now. What else needs to be changed from your point of view?

**Comment by Taki21** [comment]
@ecoron  changing back to default... only for global and main limit...keeping compression level

**Comment by Taki21** [comment]
Should "9" be good default compression level?

**Comment by robske110** [comment]
It does not help to only decrease (or disable) the memory limit! It just makes things worse, and if it runs on WinStupid it could even damage the system! The compressiom level has NOTNING to do with RAM it has to do with CPU and Network load, and i always had it on 9, as i have an realy bad network!

**Comment by Taki21** [comment]
Sorry! but a bad network is not our problem plus its working with me and some others, as said in your issue.

**Comment by Taki21** [comment]
Thats why you look at crashdumps...and all i've seen is something like $this->compressionlevel somethin like that...

**Comment by ecoron** [comment]
it doesn't depent on on the network level. a compression of 9 means, it compress it bery strong. this needs cpu... it's also a setting depending on the available cpu power, i would suggest something between 5-7 as a default value

**Comment by Taki21** [comment]
hmm. maybe this wont help but it works for me...i thought it would work in general

**Comment by ecoron** [comment]
@keithkfng i tried to confirm my account on the forum, 3 or 4 times, but i'm always see the message that i have to confirm. on confirming i'm redirected to a german 404 hoster page... maybe this should be checked too ;)

**Comment by keithkfng** [comment]
@ecoron I will confirm it for you.

**Comment by ecoron** [comment]
@keithkfng thx. It's mitnight here, so i come back tomorrow,
and we can stop the offtopic here...

**Pull request closed without merging**
