### PR TITLE
0.14 Compatibility

### PR DESCRIPTION
**Pull request by keithkfng**
**DO NOT DELETE - LEAVE THIS IN YOUR PR**
Welcome to the ImagicalMine pull request system!
Before you make an issue, make sure your pull request matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.
- [x] This PR actually submits something - don't use this system as a messaging service!
- [x] This PR isn't duplicated - you can check if it is by scanning the small list - link is on the navigation bar for this repository.
- [x] This PR includes appropriate markdown for sections - e.g. code blocks for suggested code.
- [x] This PR description and comments in code is understandable - feel free to use your native language to write if you are not comfortable with English.
- [x] This PR matches the contributing guidelines - the link is just above the title field.
- [x] This PR has a single branch for itself in your fork - don't just commit to the master branch of your repository!
- [x] This PR has comments written in clear English - please don't write unreadable comments just for your eyes.
- [ ] This PR has descriptive titles for commits - don't use "Updated <file-name>" as your title for all your commits in the PR.
If your PR matches this criteria, hooray! Submit this PR with no worries. If your PR doesn't match this criteria, please consider editing your PR to match it. Thanks for contributing to ImagicalMine!<br>
--START PR DETAILS BELOW--<br>
@ImagicalMine/developers mind helping me out solving the conflicts? XD

### CODE REVIEW

**Comment by PocketKiller** [comment]
conflicts...

**Comment by ecoron** [comment]
Please dont try to merge this in master, this will fail. 
If we want php7-0.14 as the official master then we can do this by replacing the branches (maybe i can help with that). master has a some dirty issues in its commit history and so on, and we have made some changes on ph7-0.14 which are not compatible with the master.
so i would recommend to use php7-0.14 later on as the new master.

**Comment by keithkfng** [comment]
Yes I was thinking about just simply replacing it XD

**Comment by PocketKiller** [comment]
can I make a merge commit using git?

**Comment by keithkfng** [comment]
Sure!

**Comment by ecoron** [comment]
ok so i will do it. whats about the install and setup scripts, i'm a little bit lost between the versions... 

maybe we can discuss it in the forum... and my updated client sucks too, can't connect to anywhere shows me the servers in the list but nothing more... :(

**Comment by keithkfng** [comment]
The forums are down - sorry LOL

**Comment by PocketKiller** [comment]
CPU... I hate Hostinger see?

**Comment by ecoron** [comment]
damn a lot of people there. ok so i will change the branches in the next minutes 
master -> 0.13.2
php7-0.14 -> master

mabe there is something more to update after that

**Comment by PocketKiller** [comment]
LMAO

**Comment by ecoron** [comment]
so it's hopefully successfull done ...

**Pull request closed without merging**
