### PR TITLE
fix slapper

### PR DESCRIPTION
**Pull request by Driesboy**

### CODE REVIEW

**Comment by robske110** [comment]
Lol, exactly the same as #670

**Comment by Driesboy** [comment]
haha

**Comment by Driesboy** [comment]
this work i have test on on mac :+1:

**Comment by robske110** [comment]
Yes mine does work too

**Comment by Driesboy** [comment]
can you merge this

**Comment by robske110** [comment]
We must find out wich is better
(Mine checks for NULL yours for if it is an player)

**Comment by Driesboy** [comment]
ok

**Comment by Driesboy** [comment]
but you have make more changes than me haha

**Comment by robske110** [comment]
Finally merged

**Pull request merged**
