### PR TITLE
Fixes DevTools

### PR DESCRIPTION
**Pull request by jjplaying**
- [x] This PR actually submits something - don't use this system as a messaging service!
- [x] This PR isn't duplicated - you can check if it is by scanning the small list - link is on the navigation bar for this repository.
- [x] This PR includes appropriate markdown for sections - e.g. code blocks for suggested code.
- [x] This PR description and comments in code is understandable - feel free to use your native language to write if you are not comfortable with English.
- [x] This PR matches the contributing guidelines - the link is just above the title field.
- [x] This PR has a single branch for itself in your fork - don't just commit to the master branch of your repository!
- [x] This PR has comments written in clear English - please don't write unreadable comments just for your eyes.
- [x] This PR has descriptive titles for commits - don't use "Updated <file-name>" as your title for all your commits in the PR.
- [x] This PR contains appropriate credit and clearly states the source in the description of commits.

## Pull Request description

Fixes a bug because DevTool's makeplugin command does not work any more, because there is a own makeplugin command in ImagicalMine which does not work. With the fix, everything works now. Here's also a discussion about it: https://forums.imagicalmine.net/threads/please-remove-or-fix-makeplugin.796/

### CODE REVIEW

**Comment by remotevase** [comment]
Why'd you close it?

**Comment by jjplaying** [comment]
Oh, I think I've mixed up the pull request :)

**Comment by remotevase** [comment]
No files changed?!?!?! AAAAAHHH

**Comment by jjplaying** [comment]
No wait, there are no files to change, thats the reason why I closed it.

**Comment by jjplaying** [comment]
Okay I'm using GitHub for not so long time, I'll do another Pull Request, that one should work :D

**Comment by remotevase** [comment]
Thanks, that PR worked! #231449

**Pull request closed without merging**
