### PR TITLE
Create ItemFrame.php

### PR DESCRIPTION
**Pull request by TheKnightGamer**
- [ ] This PR actually submits something - don't use this system as a messaging service!
- [ ] This PR isn't duplicated - you can check if it is by scanning the small list - link is on the navigation bar for this repository.
- [ ] This PR includes appropriate markdown for sections - e.g. code blocks for suggested code.
- [ ] This PR description and comments in code is understandable - feel free to use your native language to write if you are not comfortable with English.
- [ ] This PR matches the contributing guidelines - the link is just above the title field.
- [ ] This PR has a single branch for itself in your fork - don't just commit to the master branch of your repository!
- [ ] This PR has comments written in clear English - please don't write unreadable comments just for your eyes.
- [ ] This PR has descriptive titles for commits - don't use "Updated <file-name>" as your title for all your commits in the PR.
- [ ] This PR contains appropriate credit and clearly states the source in the description of commits.

### CODE REVIEW

**Comment by TheKnightGamer** [comment]
Now ItemFrame works

**Comment by remotevase** [comment]
lol yeah :+1:

**Comment by TheKnightGamer** [comment]
Now for maps to be made and ImagicalMine will be the best

**Comment by TheDragonRing** [comment]
:)

**Comment by keithkfng** [comment]
Somebody work on Redstone please :)

**Comment by keithkfng** [comment]
@ImagicalMine/developers Somebody finish redstone, enchanting and potions please :)

**Comment by TheKnightGamer** [comment]
I can work on enchanting and a little of redstone

**Comment by remotevase** [comment]
II may be able to work on redstone

**Comment by TheKnightGamer** [comment]
OK

**Comment by AmiroEmad** [comment]
if you think that someone copied something you must prove it first

**Comment by legoboy0215** [comment]
You people are ruining ImagicalMine's reputation. Please. Stop copying.

**Pull request merged**
